# Generated by Django 4.1 on 2022-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('malumot', models.TextField()),
                ('narxi', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
